language: generic
sudo: required
services:
  - docker

env:
  COMPOSE_VERSION: 1.18.0

before_install:
 - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose
 - sudo mv docker-compose /usr/local/bin

install:
  - docker-compose pull

before_script:
  - docker-compose build
  - docker-compose run --rm broker ./rebar get-deps
  - docker-compose run --rm broker ./rebar compile
  - docker-compose run --rm web bundle install
  - docker-compose run --rm web rake db:setup
  - docker-compose run --rm web rake db:test:prepare

script:
  - docker-compose run --rm web rspec
  - docker-compose run --rm broker make eunit

notifications:
  slack:
    secure: GpzXwTvHwT3GV8QXktjODXPvXvmxV5CmJNu+MPKe1t4OGrtORRocZgEsmyH/rahuqq7zFCMGqLg4x2nKhLIcGM1+sleTz9lEPVSqE2jmk0NOwyrwa0G16dURZH4x8bb9w+EFaciGD2x83VkhaAaYdXpPXJ9SSqxdp66/0TRkQ6k=
