version: '2.0'

services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - db:/var/lib/mysql

  broker:
    build: ./broker
    environment:
      AMI_HOST: 'asterisk'
    volumes:
      - ./broker:/app
      - asterisk:/usr/local/etc/asterisk
      - sounds:/usr/local/var/lib/asterisk/sounds
      - deps:/app/deps
      - ebin:/app/ebin
    depends_on:
      - db
    tty: true

  web: &rails
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      RAILS_ENV:
      DATABASE_HOST: 'db'
      BROKER_HOST: 'broker'
      BROKER_PORT: 9999
    pid: host
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    tmpfs: /app/tmp
    depends_on:
      - db
      - asterisk
    command: rails server -b 0.0.0.0 -p 80
    ports:
      - 3001:80

  asterisk:
    image: respoke/asterisk:13.15
    volumes:
      - asterisk:/usr/local/etc/asterisk
      - sounds:/usr/local/var/lib/asterisk/sounds

volumes:
  db:
  bundle:
  asterisk:
  sounds:
  deps:
  ebin:
