broker_port: <%= ENV["BROKER_PORT"] || 9999 %>
broker_host: <%= ENV["BROKER_HOST"] || '127.0.0.1' %>
ispeech_format: mp3
asset_host: "http://default-domain.com"
skip_account_confirmation: false
default_url_options:
  host: "default-domain.com"
  protocol: "http"
default_mailer_options:
  from: "verboice@instedd.org"
